kind: pipeline
name: "Build Project"

steps:
  - name: assets
    pull: always
    image: happymonkey/node-sass:latest
    environment:
      FONTAWESOME_NPM_AUTH_TOKEN:
        from_secret: fontawesome_npm_auth_token
    commands:
      - yarn install
      - sass --load-path=public/vendor --style=compressed public/assets/scss/:public/assets/css/

  - name: build
    pull: always
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: dockerfolder
        path: /root/.docker/
    environment:
      DOCKER_REPO: template
    commands:
      - export TAG_NAME=$(echo $DRONE_BRANCH | cut -d'/' -f 2)
      - docker build -f Dockerfile -t happymonkey/$DOCKER_REPO:$TAG_NAME .
      - docker push happymonkey/$DOCKER_REPO:$TAG_NAME
    when:
      branch:
        include:
          - release/*

type: docker

trigger:
  branch:
    - release/*

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: dockerfolder
    host:
      path: /root/.docker/