version: '2'

services:
  sass:
    image: happymonkey/node-sass:latest
    working_dir: /usr/src/app
    command: ['-c', 'sass --watch --load-path=public/vendor --style=compressed public/assets/scss/:public/assets/css']
    volumes:
      - ./:/usr/src/app
    stdin_open: true
    tty: true
    entrypoint: /bin/sh

  database:
    image: mariadb:10.5.8
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION']
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd
    stdin_open: true
    tty: true

  app:
    build:
      context: .
    environment:
      CI_ENVIRONMENT: development
      BASE_URL: http://localhost:8080
      MYSQL_HOST: database
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd
      MYSQL_PORT: 3306
      EMAIL_HOST: mailhog
      EMAIL_USER:
      EMAIL_PASSWORD:
      EMAIL_SECURE: 0
      EMAIL_PORT: 1025
    stdin_open: true
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
      - 9000:9000
      - 8282:8282
    depends_on:
      - database
    links:
      - database

  nginx:
    image: happymonkey/nginx-php
    stdin_open: true
    tty: true
    volumes_from:
      - app
    ports:
      - 8080:80
    depends_on:
      - app
    links:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: database
      PMA_USER: user
      PMA_PASSWORD: pwd
    ports:
      - 8001:80
    volumes:
      - /sessions
    depends_on:
      - database
    links:
      - database

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025