version: '2'

services:
  sass:
    container_name: ${COMPOSE_PROJECT_NAME}-sass
    image: happymonkey/node-sass:latest
    working_dir: /var/www/app
    command: ['-c', 'sass --watch --load-path=public/vendor --style=compressed --error-css public/assets/scss/:public/assets/css']
    volumes:
      - ./:/var/www/app
    stdin_open: true
    tty: true
    entrypoint: /bin/sh

  database:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: mariadb:10.5.8
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION']
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    stdin_open: true
    tty: true

  app:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      CI_ENVIRONMENT: development
      FORCE_HTTPS: false
      BASE_URL: http://localhost:8080
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      EMAIL_FROM: noreply@mkey.dev
      EMAIL_FROM_NAME: Happy Monkey
      EMAIL_HOST: mailhog
      EMAIL_USER:
      EMAIL_PASSWORD:
      EMAIL_SECURE:
      EMAIL_PORT: 1025
    stdin_open: true
    tty: true
    volumes:
      - ../:/var/www/app
    ports:
      - '8080:80'
    depends_on:
      - database
    links:
      - database

  phpmyadmin:
    container_name: ${COMPOSE_PROJECT_NAME}-pma
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: ${MYSQL_HOST}:${MYSQL_PORT}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      UPLOAD_LIMIT: ${PMA_UPLOAD_LIMIT}
    ports:
      - '8001:80'
    volumes:
      - /sessions
    depends_on:
      - database
    links:
      - database

  mailhog:
    container_name: ${COMPOSE_PROJECT_NAME}-mailhog
    image: mailhog/mailhog
    ports:
      - '8025:8025'